### ISSUE TITLE
floating point exception in emacs eshell

### ISSUE THREAD

**Issue by cacocodix** [grzegorzmazur/yacas#126]
In some terminals, e.g. emacs eshell the `ws_col` is set to o and the following code produces a floating point exception:
unixcommandline.cpp
````c
    ioctl(0, TIOCGWINSZ, &w);
    const std::size_t prompt_len = prompt.length();
    const LispInt l = (cursor + prompt_len) / w.ws_col;
    const LispInt c = (cursor + prompt_len) % w.ws_col;

```` 

strace:
````     
write(1, "To see example commands, keep ty"..., 48To see example commands, keep typing Example();
) = 48
ioctl(0, TIOCGWINSZ, {ws_row=0, ws_col=0, ws_xpixel=0, ws_ypixel=0}) = 0
--- SIGFPE {si_signo=SIGFPE, si_code=FPE_INTDIV, si_addr=0x409e50} ---
+++ killed by SIGFPE +++
floating point exception
````
A quick and ugly patch would be to introduce a default non-zero `ws_col` value to avoid raising the FPE.
Thanks!

**Comment by grzegorzmazur** [comment]
Right, it's been bothering me for a while now. The issue shows up in some terminals, like eterm you've mentioned or the netbeans internal terminal. Apparently it can be handled correctly, for example the less command deals with all them. The easiest way would be to use ncurses, but I'm hesitant about adding an external dependency.
