### ISSUE TITLE
Makefile.am: error: required file './README' not found [sf#96]

### ISSUE THREAD

**Issue by martanoga** [grzegorzmazur/yacas#164]
README.rst is there but automake insists on even more plaintext one around. :) (it's fine with an empty one though)

Originally reported by [Michael Shigorin](https://sourceforge.net/u/gvy/profile/) on SF: https://sourceforge.net/p/yacas/tickets/96/

**Comment by grzegorzmazur** [comment]
in the makemake script automake is called with --foreign flag, specifically to avoid this issue
