### ISSUE TITLE
broken src/Makefile (spaces vs tabs) [sf#97]

### ISSUE THREAD

**Issue by martanoga** [grzegorzmazur/yacas#165]
someone (or their software wrongly named text editor) violated makefile syntax while adding several more lines; please see the attached patch for the fixup.
PS: guys, 1.4.0 looks pretty much a misrelease by now, did anyone try actually building it on Linux?
PPS: used it since 2001 or so, many thanks for the nice piece of software -- still have 1.0.45 installed on one of my systems to check that old binaries still work :-)

Originally reported by [Michael Shigorin](https://sourceforge.net/u/gvy/profile/) on SF: https://sourceforge.net/p/yacas/tickets/97/

**Comment by grzegorzmazur** [comment]
thanks, applied with minor modifications

PS: I actually quite like it, and yes, it does build on linux
PPS: you're welcome :)
PPPS: please use the new bugtracker to report issues
