### ISSUE TITLE
sphinx problem in building yacas 1.5.0  (Linux, Fedora 22)

### ISSUE THREAD

**Issue by mmaechler** [grzegorzmazur/yacas#195]
The following  (in Fedora 22 Linux, in a bash):

-   tar xfz yacas-1.5.0.tar.gz
-   cd yacas-1.5.0/
-   mkdir build
-   cd build
-   cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=On ..
-   make

ended in error:   I am reporting it here ... even so it suggests the error is in 'sphinx'

-----------------------------------------------------------------------------
........
[ 90%] Linking CXX static library libyacas.a
[ 90%] Built target libyacas
Scanning dependencies of target yacas
[ 92%] Building CXX object CMakeFiles/yacas.dir/src/yacasmain.cpp.o
[ 95%] Building CXX object CMakeFiles/yacas.dir/src/unixcommandline.cpp.o
[ 97%] Linking CXX executable yacas
[ 97%] Built target yacas
Scanning dependencies of target yacas_docs
[100%] Building HTML documentation with Sphinx

Exception occurred:
  File "conf.py", line 113, in <module>
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /tmp/sphinx-err-xC9898.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
docs/CMakeFiles/yacas_docs.dir/build.make:57: recipe for target 'docs/CMakeFiles/yacas_docs' failed
make[2]: *** [docs/CMakeFiles/yacas_docs] Error 1
CMakeFiles/Makefile2:1073: recipe for target 'docs/CMakeFiles/yacas_docs.dir/all' failed
make[1]: *** [docs/CMakeFiles/yacas_docs.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

------------------- and here is the  /tmp/....err...log file :

more  /tmp/sphinx-err-xC9898.log
```
# Sphinx version: 1.2.3
# Python version: 2.7.10
# Docutils version: 0.12 repository
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 113, in <module>
ImportError: No module named sphinx_rtd_theme
```
-------------------------------------------------------------------------------------------------------

I don't know sphinx; I really like to use yacas (via the R package 'Ryacas')...
and whereas the executable is built by the above,
with the missing documentation, many things do not work.

**Comment by grzegorzmazur** [comment]
It's missing python-sphinx_rtd_theme package; install it and compilation should work. Additionally, on http://www.yacas.org/getting_started/downloads/ you'll find yacas packages for Fedora 22
