### ISSUE TITLE
Scientific notation in jyacas

### ISSUE THREAD

**Issue by qwert2003** [grzegorzmazur/yacas#210]
Expression with scientific notation
7.4694E-5 - 7.0171E-5

jyacas:
This is Yacas version '1.5.0'.
...
Yacas in Java
In> **7.4694E-5 - 7.0171E-5**
Out> **0.4523**

cyacas:
This is Yacas version '1.5.0'.
...
In> 7.4694E-5 - 7.0171E-5
Out> **0.4523e-5**

Expected result:
As in cyacas

**Comment by grzegorzmazur** [comment]
Adrian, thanks a lot!

**Comment by qwert2003** [comment]
Commit 22f4188 only partially fixes the issue with scientific notation.
**It seems notation `4.0e-3` works while the notations `4.e-3` and `4e-3` still have issues.**

Expression `4e-3 - 1e-3` fails in jyacas (current develop branch) while working in cyacas.
Expression `3.e-3 * 1` also fails in jyacas while working in cyacas.
See below.

_Test cases_
In> 0.004 - 0.001
cyacas Out> 0.003
jyacas Out> 0.003

In> 4.0e-3 - 1.0e-3
cyacas Out> 0.3e-2
jyacas Out> 3e-3

**In> 4.e-3 - 1.e-3**
cyacas Out> 0.3e-2
**jyacas Out> 3**

**In> 4e-3 - 1e-3**
cyacas Out> 0.3e-2
**jyacas Out> 3**

**In> 3.e-3 * 1**
cyacas Out> 0.3e-2
**jyacas Out> 3**


_Systematic tests_  (jyacas only)
```
0.004 - 0.001 --> 0.003
4.0e-3 - 1.0e-3 --> 3e-3
4.e-3 - 1.e-3 --> 3
4e-3 - 1e-3 --> 3

4.0e-3 - 1e-3 --> 3e-3
4.0e-3 - 1.e-3 --> 3e-3
4e-3 - 1.0e-3 --> 3e-3
4.e-3 - 1.0e-3 --> 3e-3

3.0e-3 * 1 --> 3e-3
1 * 3.0e-3 --> 3e-3
3.0e-3 * 1. --> 3e-3
1. * 3.0e-3 --> 3e-3
3.0e-3 * 1.0 --> 3e-3
1.0 * 3.0e-3 --> 3e-3

3.e-3 * 1 --> 3
1 * 3.e-3 --> 3
3.e-3 * 1. --> 3
1. * 3.e-3 --> 3
3.e-3 * 1.0 --> 3e-3
1.0 * 3.e-3 --> 3e-3

3e-3 * 1 --> 3
1 * 3e-3 --> 3
3e-3 * 1. --> 3
1. * 3e-3 --> 3
3e-3 * 1.0 --> 3e-3
1.0 * 3e-3 --> 3e-3
```


_Testing environment_
- jyacas, current develop branch (commit 22f4188 applied)
- cyacas 1.5.0
