### ISSUE TITLE
enhancement request: have cmake create "make install" targets

### ISSUE THREAD

**Issue by ilovezfs** [grzegorzmazur/yacas#225]
Currently, there is no "make install" available as far as I can tell, so the Homebrew formula ends up looking like this:
```
  depends_on "cmake" => :build
  depends_on :xcode => :build

  def install
    mkdir "build" do
      system "cmake", "..", "-G", "Xcode", "-DENABLE_CYACAS_GUI=OFF",
                            "-DENABLE_CYACAS_KERNEL=OFF", *std_cmake_args
      xcodebuild "-target", "ALL_BUILD", "-project", "YACAS.xcodeproj",
                 "-configuration", "Release", "SYMROOT=build/cyacas/libyacas"
    end
    bin.install "build/cyacas/libyacas/Release/yacas"
    lib.install Dir["build/cyacas/libyacas/Release/{libyacas.a,yacas.framework}"]
    pkgshare.install "scripts"
  end
```

It would be great if we could instead do this:
```
  depends_on "cmake" => :build
  depends_on :xcode => :build

  def install
    mkdir "build" do
      system "cmake", "..", "-G", "Xcode", "-DENABLE_CYACAS_GUI=OFF",
                            "-DENABLE_CYACAS_KERNEL=OFF", *std_cmake_args
      system "make", "install"
    end
  end 
```
Thanks!

**Comment by grzegorzmazur** [comment]
It's a bit surprising, cmake generates the install target automatically. It's posssible in the case of yacas it doesn't work correctly on macOS, the whole framework/application bundle approach is specific enough to warrant some issues. I'll try to fix it once I get access to a mac machine. In the meantime, could you please describe what happens when you try to run ``make install``?

**Comment by ilovezfs** [comment]
There's no Makefile at all, so it fails on target not found.

**Comment by grzegorzmazur** [comment]
Right, now that I've actually had a look at the code, I think I understand the issue. 
```
    system "cmake", "..", "-G", "Xcode", "-DENABLE_CYACAS_GUI=OFF",
                            "-DENABLE_CYACAS_KERNEL=OFF", *std_cmake_args
```
instructs cmake to generate Xcode project. Given that, installation can be performed by
```
    xcodebuild "-target", "install", "-project", "YACAS.xcodeproj", "-configuration", "Release"
```
(note, it's from the top of my head and not tested at all).

If you'd rather avoid invoking xcodebuild, you can either use
```
    cmake --build . --target ALL_BUILD --config Release
    cmake --build . --target install --config Release
```
(again, it's from the top of my head and not tested at all) or check if cmake on macOS supports the makefile generator and use it.

I can check it all but it'll tak a couple of days until I have access to any mac.

BTW, what "SYMROOT=build/cyacas/libyacas" is supposed to mean?
