### ISSUE TITLE
yacas-1.6.1.tar.gz (source code) doesn't exist on sourceforge.net/projects/yacas/

### ISSUE THREAD

**Issue by Petross404** [grzegorzmazur/yacas#226]
https://sourceforge.net/projects/yacas/

I am a gentoo user who wish to update the old yacas (1.3.4) that exists in Portage, to yacas-1.6.1.

Although I can download the source code from github's release page, the official packagement downloaded the previous releases from sourceforge. Do you think you could move the new tarball over here as well?

Thank you. :-)

**Comment by grzegorzmazur** [comment]
I'd rather ask the gentoo yacas maintainers to update the yacas portage. While I could upload a copy of new files to sourceforge, it's over a year (and three releases) now that yacas development was transferred to github. But the important point is that the build procefure has changed significantly in the meantime, so just uploading the new tarball wouldn't work. I'll try to come up with a new portage overlay, but it's not really my area of expertise, so I can't guarantee success.

**Comment by Petross404** [comment]
Oh that's ok then. So the source can be downloaded from github if **that's** the way ;)

I am aware of the changes and I am trying to write this new ebuild with _cmake_ configuration in mind.

Pardon my ignorance, but are Boost, openssl and valgrind optional dependencies? I mean, could someone disable them via USE Flags and Yacas stil work?
