### ISSUE TITLE
Yacas-GUI 1.6.1 refuses input after typing a '#' (Mac OS X)

### ISSUE THREAD

**Issue by genivia-inc** [grzegorzmazur/yacas#231]
For example, when entering:
`in: Infix(##,0);`
Yacas refuses any further input (or does not display the input being entered).

Hope a fix will make Yacas even better!

**Comment by grzegorzmazur** [comment]
It shows up on linux as well.

**Comment by grzegorzmazur** [comment]
the patch is on it's way upstream: https://github.com/codemirror/CodeMirror/pull/4790
