### ISSUE TITLE
Fail to evaluate limit when using jar archive (version 1.6.1)

### ISSUE THREAD

**Issue by djpesic** [grzegorzmazur/yacas#232]
When i try to evaluate  Limit(x,0) Sin(x)/x, using 1.6.1 jar fail, net.sf.yacas.YacasException: Trying to modify protected symbol is thrown. Test program:

public static void main(String[] args){
 try {
            YacasInterpreter in = new YacasInterpreter();
            System.out.println(in.Evaluate("Limit(x,0)Sin(x)/x"));
        } catch (IOException ex) {
            Logger.getLogger(proba.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(proba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

**Comment by grzegorzmazur** [comment]
Suprisingly, the issue doesn't show up in cyacas, even though they should behave exactly the same with respect to symbol protection

**Comment by djpesic** [comment]
Yeah, that is right. When i compiled native version (both on linux and windows) everything works ok with limit calculation.

**Comment by qwert2003** [comment]
It seems the method `LispEnvironment.DeclareRuleBase(...)` causes the error, when it checks whether the aOperator "Sign" is protected.
And it is protected, maybe by `LispStandard.DoLoadDefFile` "stubs.rep/code.ys" and  `LispStandard.InternalUse(...)`, thus the exception is raised.

The method `LispEnvironment.DeclareRuleBase(...)` is called by scripts/limit.rep/code.ys:
```
UnProtect(Sign);

/*  To get the sign of the denominator on one side:  */
Sign(_var, _tar, _dir, _exp, _n)
<-- [
  Local(der, coef); der := ApplyPure("D", {var, exp});
  coef := Eval(ApplyPure("Subst", {var, tar, der}));
  If ( coef = 0,
       Sign(var, tar, dir, der, n+1),
       (Sign(coef)*Dir(dir)) ^ n
     );
];

Protect(Sign);
```

It looks like the command "`UnProtect(Sign);`" in scripts/limit.rep/code.ys had no effect in jyacas.

Work around:
If you cut the code `Sign(_var, ...) <-- ...` quoted above ( without UnProtect(Sign) and Protect(Sign) ) from limit.rep/code.ys and paste it into stubs.rep/code.ys then the input `Limit(x,0) Sin(x)/x` returns 1 in jyacas.

**Comment by grzegorzmazur** [comment]
OK, so this is a symptom of a more general issue with dependencies. Standard definition of Sign() is provided by stubs.rep as a lazy (load on demand) symbol. At the same time special case defined in limit.rep implicitly assumes that Sign() is already defined (loaded).

I have to think more about a better solution, but as a stopgap measure I just call Sign(1) before attempting to extend the definition of Sign(), this way forcing the standard definition of Sign() to be loaded early enough.
