### ISSUE TITLE
press control-D to exit

### ISSUE THREAD

**Issue by medovina** [grzegorzmazur/yacas#233]
Yacas is great!

It would be nice if I could press control-D to exit (since that works in just about every other command-line Linux program).

**Comment by grzegorzmazur** [comment]
Thanks :)

With respect to control-D: it's just that nobody has thought about it yet. But now, as you've asked, I'm going to implement it the same way it works in other popular console programs, which is exiting the program if control-D is pressed in an empty line and doing nothing otherwise.

**Comment by medovina** [comment]
Sounds good!
