### ISSUE TITLE
error occured when build SHARED kernel library.

### ISSUE THREAD

**Issue by juncy** [grzegorzmazur/yacas#242]
When build the SHARED Yacas kernel lib with `yacas/cyacas/libyacas/CMakeLists.txt`, we got error:

> Make Error at CMakeLists.txt:98 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "libyacas".

> 

And we add `LIBRARY DESTINATION lib` solved the problem.

**Comment by grzegorzmazur** [comment]
Thanks for spotting this! Would you mind providing a pull request please?
