### ISSUE TITLE
Limit lim(ln(x)) when x->inf returns wrong value

### ISSUE THREAD

**Issue by djpesic** [grzegorzmazur/yacas#250]
The result is ln(Infinity), instead of Infinity.

**Comment by grzegorzmazur** [comment]
`Limit(x,Infinity)Ln(x)` works as expected, yielding `Infinity`. Your report lacks specific steps to reproduce, but I suspect that the reason is that you use `ln(x)` instead of `Ln(x)` (all standard names in yacas start with capital letter).
