### ISSUE TITLE
List variables

### ISSUE THREAD

**Issue by mikldk** [grzegorzmazur/yacas#253]
Can I list all variable bindings? In same family as `Set()`, `Clear()` etc. E.g. `ListVariables()`?

**Comment by grzegorzmazur** [comment]
Unfortunately not; there's some internal code doing just this for the command-completion purpose, but it's not a user-accessible function. It looks like a reasonable extension and should be fairly easy to add, I'll give it a try some time next week.

**Comment by grzegorzmazur** [comment]
Given the purpose, don't you really need names of all defined symbols, including eg functions? Or perhaps names of the protected symbols?

**Comment by mikldk** [comment]
I have thought about it, and I'm not sure. I think mainly it will be used to help the user with variables (distinguishing between R and yacas). Hence I think for now variables is sufficient, but I agree it makes sense to think through for other uses. 

Maybe a function returning variables only and one returning all. Or just one returning all and then the origin/type (variable, function, ...)?

**Comment by grzegorzmazur** [comment]
OK, to be honest I'm not sure either at the moment, so I've just implemented Variables() function. It returns names of all global variables except for special internal ones which have names starting with $ and except variable containing the last evaluated expression named %. Other then that all the names are returned in a list. This way you can start experimenting with it. Should any change in functionality be required, just let me know.

**Comment by mikldk** [comment]
Thank you very much! Looking forward to trying it out.

**Comment by mikldk** [comment]
I have tried it, and it is exactly what I needed. Thanks. You are welcome to close this unless you think something is missing.
