### ISSUE TITLE
RForm: Pi

### ISSUE THREAD

**Issue by mikldk** [grzegorzmazur/yacas#280]
As reported on <https://github.com/mikldk/ryacas/issues/31> it seems like `RForm()` does not handle `Pi` properly. Maybe a line in [`r_form.rep/code.ys`](https://github.com/grzegorzmazur/yacas/blob/master/scripts/r_form.rep/code.ys#L164) is needed, e.g. `{"Pi","pi"},`, although I am not sure if it should be listed among functions or have its own rule.

**Comment by grzegorzmazur** [comment]
Right, I've missed this one. There's no translation table for constants (there were only two till now, True and False), so I've just added another rule for Pi.

**Comment by mikldk** [comment]
Thank you very much!
