### ISSUE TITLE
TeXForm brackets

### ISSUE THREAD

**Issue by mikldk** [grzegorzmazur/yacas#285]
`TeXForm(Sin(a*x))` gives me `\sin a x`. Can I somehow instruct `yacas` to put brackets to obtain `\sin \left ( a x \right )`? I know there is various opinions, but in this case I need it. So I am not seeking a change in `yacas` but maybe a `yacas` rule or option to get what I need for my current session.

**Comment by mikldk** [comment]
Maybe this is a global fix:
```
# texform.rep/code.ys
-  120 # TeXForm(expr_IsFunction, _p) _ (NrArgs(expr)=1 And Contains(AssocIndices(TeXFormMathFunctions), Type(expr)) ) <-- TeXFormBracketIf(p<OpPrecedence("*"), ConcatStrings(TeXFormMathFunctions[Type(expr)], TeXForm( Listify(expr)[2], OpPrecedence("*")) ) );
+  //120 # TeXForm(expr_IsFunction, _p) _ (NrArgs(expr)=1 And Contains(AssocIndices(TeXFormMathFunctions), Type(expr)) ) <-- TeXFormBracketIf(p<OpPrecedence("*"), ConcatStrings(TeXFormMathFunctions[Type(expr)], TeXForm( Listify(expr)[2], OpPrecedence("*")) ) );
+  120 # TeXForm(expr_IsFunction, _p) _ (NrArgs(expr)=1 And Contains(AssocIndices(TeXFormMathFunctions), Type(expr)) ) <-- ConcatStrings(TeXFormMathFunctions[Type(expr)], "\\left( ", TeXForm( Listify(expr)[2], OpPrecedence("*")), "\\right) "); 
```

Though not at all sure the code is at it should be (as my `yacas` skills are still very limited).

**Comment by mikldk** [comment]
Maybe this is a global fix:
```
# texform.rep/code.ys
   // generic math functions of one argument
-  120 # TeXForm(expr_IsFunction, _p) _ (NrArgs(expr)=1 And Contains(AssocIndices(TeXFormMathFunctions), Type(expr)) ) <-- TeXFormBracketIf(p<OpPrecedence("*"), ConcatStrings(TeXFormMathFunctions[Type(expr)], TeXForm( Listify(expr)[2], OpPrecedence("*")) ) );
+  120 # TeXForm(expr_IsFunction, _p) _ (NrArgs(expr)=1 And Contains(AssocIndices(TeXFormMathFunctions), Type(expr)) ) <-- TeXFormBracketIf(p<OpPrecedence("*"), ConcatStrings(TeXFormMathFunctions[Type(expr)], TeXForm( Listify(expr)[2], OpPrecedence("^")) ) ); 
```

I.e. replacing the last `OpPrecedence("*")` with `OpPrecedence("^")`. Can I somehow override such a rule in my local session? Or maybe make it an an option somewhere?

**Comment by grzegorzmazur** [comment]
Hi,

I've just committed a fix based on your idea, only with a new parameter TeXForm'FuncPrec.  It allows for setting the precedence without modifying the rule.

Cheers,
Grzesiek

**Comment by mikldk** [comment]
Thanks!

Should it check for a positive number instead of just a number?

**Comment by grzegorzmazur** [comment]
Hi,

I'd rather not silently override user settings, even if silly. In principle I should have checked if it evaluates to anything other than itself, checking for a number is already cheating 😉

Grzesiek
