### ISSUE TITLE
man page of yacas, option -c

### ISSUE THREAD

**Issue by MarcoCostantini** [grzegorzmazur/yacas#289]
Please fix the man page of yacas, that says:

       -c        Inhibit printing of prompts "In>" and "Out>". Useful for non-interactive sessions.

but the -c option inhibits the initial banner, not the prompt
If fact:

$ yacas -c
In> 4+5
Out> 9
In>

**Comment by grzegorzmazur** [comment]
Hi,

Actually this is a bug and not documentation issue.

Grzesiek

**Comment by MarcoCostantini** [comment]
Hi

also an option that just removes the banner can be useful

**Comment by grzegorzmazur** [comment]
Ok, makes sense, Thanks for the idea :)

**Comment by MarcoCostantini** [comment]
Hi
Now in [https://github.com/grzegorzmazur/yacas/blob/master/man/yacas.1.rst](https://github.com/grzegorzmazur/yacas/blob/master/man/yacas.1.rst) there is `-c` twice.
I think it would be better to leave the behavior of -c unchanged, and to add a different letter for removing the prompt

**Comment by grzegorzmazur** [comment]
Ups, good catch! This time it is a documentation bug, and the actual functionality is exactly as you suggested.

Thanks,
Grzesiek
