### ISSUE TITLE
OpenMath in Yacas, part 2

### ISSUE THREAD

**Issue by MarcoCostantini** [grzegorzmazur/yacas#294]
############ NaN, INF, -INF

When converting from OpenMath to Yacas, also the floats NaN, INF, -INF should be converted.
For instance, the following should be converted to the native Yacas NaN and infinity,
&lt;OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
  &lt;OMA>
    &lt;OMS cd="list1" name="list" />
    &lt;OMF dec="NaN" />
    &lt;OMF dec="INF" />
    &lt;OMF dec="-INF" />
  &lt;/OMA>
&lt;/OMOBJ>

On the other hand, when converting from Yacas to OpenMath, these are used:
&lt;OMS cd="nums1" name="infinity"/>
&lt;OMS cd="nums1" name="NaN"/>
which is perfect.

############ OpenMath generated by Yacas doesn't validate

Currently, when converting &lt;OMF dec="-INF" /> to Yacas, -INF is treated like a variable with the name starting with a minus:
In> FromString("&lt;OMOBJ>&lt;OMF dec=\""-INF\""/>&lt;/OMOBJ> ")OMRead()
Out> -INF    
In> OMForm(%)
&lt;OMOBJ>
  &lt;OMV name="-INF"/>
&lt;/OMOBJ> 
Out> True
In>

When converting back to OpenMath, the result doesn't even validate, even if the namespace is added
&lt;OMOBJ xmlns="http://www.openmath.org/OpenMath" version="2.0" cdbase="http://www.openmath.org/cd">
  &lt;OMV name="-INF"/>
&lt;/OMOBJ>

(To validate OpenMath pieces, it can be used the online validator
[https://www.liquid-technologies.com/online-relaxng-validator](https://www.liquid-technologies.com/online-relaxng-validator)
with the grammar copied from
[https://www.openmath.org/standard/om20-2019-07-01/omstd20.html#app_openmath.rng](https://www.openmath.org/standard/om20-2019-07-01/omstd20.html#app_openmath.rng))

########### Unary minus instead of binary minus

In these cases, when converting from Yacas to OpenMath, it should be used the unary minus instead of binary minus.

In> -Pi
Out> -Pi
In> OMForm(%)
&lt;OMOBJ>
  &lt;OMA>
    &lt;OMS cd="arith1" name="minus"/>
    &lt;OMS cd="nums1" name="pi"/>
  &lt;/OMA>
&lt;/OMOBJ>

In this example, pi is in fact the subtrahend, not the minuend before a binary minus.
See also
[https://www.openmath.org/cd/arith1.html#unary_minus](https://www.openmath.org/cd/arith1.html#unary_minus)
[https://www.openmath.org/cd/arith1.html#minus](https://www.openmath.org/cd/arith1.html#minus)

Another example in which unary_minus would required instead of minus is:
In> Solve(x^2-2,x)[2][2]
Out> -Sqrt(2)
In> OMForm(%)
&lt;OMOBJ>
  &lt;OMA>
    &lt;OMS cd="arith1" name="minus"/>
    &lt;OMA>
      &lt;OMS cd="arith1" name="root"/>
      &lt;OMI>2&lt;/OMI>
      &lt;OMI>2&lt;/OMI>
    &lt;/OMA>
  &lt;/OMA>
&lt;/OMOBJ>
Out> True

**Comment by grzegorzmazur** [comment]
I've split the issue, moving the part related to unary minus to #305
