### ISSUE TITLE
no download for Ubuntu 20.04

### ISSUE THREAD

**Issue by MarcoCostantini** [grzegorzmazur/yacas#296]
The instructions in http://www.yacas.org/getting_started/downloads/ for the download of binary packages for Ubuntu don't work with the up-to-date Ubuntu 20.04, because in http://ppa.launchpad.net/teoretyk/yacas/ubuntu/dists/ there are only the directories for the previous versions of Ubuntu

**Comment by grzegorzmazur** [comment]
Hi,

I've rebuilt yacas for focal, it's now available from PPA.
Thanks a lot for reminding me, I've completely forgot about it :(

Cheers,
Grzesiek
