### ISSUE TITLE
Gcd bugs [sf#3]

### ISSUE THREAD

**Issue by grzegorzmazur** [grzegorzmazur/yacas#3]
**Reported by jleto on 2011-11-20 11:53 UTC**
In&gt; Gcd(10,3.3)  
Out&gt; 3.3; //should error with floats  

In&gt; Gcd(10,Pi)  
Out&gt; Pi; //and irrational consts  

In&gt; Gcd(Exp(1),Exp(2))  
Out&gt; Exp(2); // and functions that don't return int's  

In&gt; Gcd(-10,0)  
// according to &amp;quot;Number Theory&amp;quot;, Andrews (1971)  
// Gcd(a,0) = Abs(a)  
Out&gt; -10; //should be 10  

In&gt; Gcd(0,-10)  
Out&gt; -10; //same as previous, since Gcd(a,b) = Gcd(b,a)  

* * *

Moved from SF: 559695

**Comment by grzegorzmazur** [comment]
Actually, Gcd(Exp(1), Exp(2)) would be better off returning Exp(1)

**Comment by martanoga** [comment]
First issue reported separately as #107

**Comment by martanoga** [comment]
All issues except ones with float and irrational const resolved. Separate issue submitted - #107, #108
