### ISSUE TITLE
escaped chars and OpenMath

### ISSUE THREAD

**Issue by MarcoCostantini** [grzegorzmazur/yacas#306]
When converting from openmath to yacas (see  #298), the line `If (ec = "&amp;", s := s : "&");` must be **after** the other escapes

When converting from yacas to openmath (see https://github.com/grzegorzmazur/yacas/commit/42b7c8a53da5c0b7f2593180092c9d95f0c03079 )
add the line `c := If (c = "&", "&amp;", c);` **before** the other escapes

**Comment by MarcoCostantini** [comment]
for instance, the string `"&lt;"` must became `"<OMOBJ><OMSTR>&amp;lt;</OMSTR></OMOBJ>"` and vice versa

**Comment by grzegorzmazur** [comment]
Hi,

Are you sure? I mean your example seems to work:
```
In> OMForm("&lt;")
<OMOBJ>
  <OMSTR>&amp;lt;</OMSTR>
</OMOBJ>
Out> True
In> FromString("<OMOBJ><OMSTR>&amp;lt;</OMSTR></OMOBJ>")OMRead()
Out> "&lt;"
```
And with respect to ordering of the substitution cases, they are actually independent of each other, or at least I believe they are :) If no, could you please provide an example when the ordering does matter?

Cheers,
Grzesiek
