### ISSUE TITLE
How to get special characters like tab(escape sequence)  in Yacas

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [grzegorzmazur/yacas#311]
Hello, everyone!
How to get **escapeSeq** in Echo or Write or WriteString functions especially tab character(_\t_ or _chr(9)_ or _Char(9)_ or ...)?

**Comment by grzegorzmazur** [comment]
Hi, unfortunately it is not possible yet. But it's fairly simple to implement, I'll give it a go in next week or two.
