### ISSUE TITLE
SymbolicDeterminant fail if variable i has a value.

### ISSUE THREAD

**Issue by Isomorph70** [grzegorzmazur/yacas#321]
[i:=5;SymbolicDeterminant(Identity(3));];

**Comment by Isomorph70** [comment]
Adding an 'i' to Local seem to help.

20 # SymbolicDeterminant(_matrix) <-- [
    Local(perms,indices,result,i);
    Check((IsMatrix(matrix)),"Determinant: Argument must be a matrix");
    indices:=Table(i,i,1,Length(matrix),1);
    perms:=Permutations(indices);
    result:=0;
    ForEach(item,perms)
        result:=result+Product(i,1,Length(matrix),matrix[i][item[i] ]) * LeviCivita(item);
    result;
];

**Comment by grzegorzmazur** [comment]
Thanks, it seems to be the fix, I'll push fix that tomorrow.

Cheers,
Grzesiek
