### ISSUE TITLE
Oddity of linear functions

### ISSUE THREAD

**Issue by h-v-smacker** [grzegorzmazur/yacas#328]
Check of oddity for a linear function y=kx+b, b=0 returns false when k≠1, even though all linear functions passing through (0,0) are odd:

> IsOddFunction(x,x)
> True
> IsOddFunction(2*x,x)
> False

This doesn't affect y=k/x functions, however:

> IsOddFunction(1/x,x)
> True
> IsOddFunction(2/x,x)
> True
> IsOddFunction(2*1/x,x)
> True

Applicable to both yacas online and Ryacas 1.1.3.1.

**Comment by grzegorzmazur** [comment]
Thanks for reporting :)

Cheers,
Grzesiek
